### ISSUE TITLE
Run validation job on all supported GitLab instances 

### ISSUE THREAD

**Issue by lachmanfrantisek** [packit-service/deployment#445]
* [ ] Extend the validation script to run on all GitLab instances we have identities on.
   * [x] `gitlab.com` is covered by #401 
   * [x] `gitlab.freedesktop.org`
   * [x] `gitlab.gnome.org`
   * [x] `salsa.debian.org`
* [ ] Configure the user for each instance (similarly to `gitlab.com` added in #401)
   * [ ] `gitlab.freedesktop.org`
   * [x] `gitlab.gnome.org`
* [ ] Prepare the environment (mainly, sync the MR from `gitlab.com` created when working on #401)
   * [ ] `gitlab.freedesktop.org`
   * [x] `gitlab.gnome.org`
   * [ ] `salsa.debian.org`

Run these only once a week, e.g. Wednesday (after prod update).

For context, @mfocko has mentioned the following:
> recently we have lost a production user on gnome.org instance and the exception caught by Sentry did not suggest this option in any way, we should be able to both monitor the accessibility and uptime on other instances and verify that basic workflows are functioning

Follow-up for packit/deployment#401

---
*Part of packit/packit-service#1821 epic.*

**Comment by majamassarini** [comment]
- Waiting for the account validation email from salsa.debian.org
- Waiting for the creation of a group in gitlab.freedesktop.org (see [issue 641](https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/641#note_1895838) and [issue 648](https://gitlab.freedesktop.org/freedesktop/freedesktop/-/issues/648))
