### ISSUE TITLE
Move Openshift tests from Zuul to Testing Farm

### ISSUE THREAD

**Issue by majamassarini** [packit-service/deployment#543]
### After a deeper look, we can summarize this epic in the following steps:

  - [x] Automatically bootstrap Openshift Local in a local VM and run successfully one of our tests there (see packit/deployment/pull/562)
  - [x] Re-create the same environment used locally in a Testing Farm public bare metal instance packit/deployment#563
  - [x] Enable secrets in Testing Farm instance packit/deployment#564
  - [x] Execute successfully the first test on Testing Farm packit/deployment#565
  - [ ] Migrate all other openshift tests we have to Testing Farm and enable them in CI pipelines packit/deployment#566
  - [ ] **optional** Optimize test time execution using Snapshots (if execution time in CI is too long) 

---

### Description

We decided to setup an Openshift cluster in Testing Farm to move there the tests (at least those which needs openshift) of this repos:

 - deployment
 - packit-service
 - sandcastle

The strimzi project has a [k8s cluster setup](https://developers.redhat.com/articles/2023/08/17/how-testing-farm-makes-testing-your-upstream-project-easier#strimzi_e2e_tests) for testing farm.

David told me:
> we do install k8s cluster in scope of prepare steps in tmt plan. We used minikube and now we migrated to kind which also allows us to use multi node k8s cluster and support for ipv6.

> plan:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/systemtest/tmt/plans/main.fmf#L89

> setup-kind:
https://github.com/strimzi/strimzi-kafka-operator/blob/main/.azure/scripts/setup-kind.sh

Probably we can start easy with minikube, following their example, and later if needed replacing it with an openshift instance...

This is a follow-up from packit/research#210

**Comment by majamassarini** [comment]
Probably the best thing is to start with the Openshift instance (Matej already gave a look at minikube and probably it is not worth spending time on it).

**Comment by majamassarini** [comment]
Maybe in the new year we can work in the Packit integration for secrets in testing farm.
